package com.daffa.moviecatalogue.util

import com.daffa.moviecatalogue.data.DataModel

object DataDummy {
    fun generateMovie(): List<DataModel> = listOf(
        DataModel(
            "A Star Is Born",
            "   Seasoned musician Jackson Maine discovers — and falls in love with — struggling artist Ally. She has just about given up on her dream to make it big as a singer — until Jack coaxes her into the spotlight. But even as Ally's career takes off, the personal side of their relationship is breaking down, as Jack fights an ongoing battle with his own internal demons.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/wrFpXMNBRj2PBiN4Z5kix51XaIZ.jpg",
            "DRAMA, ROMANCE, MUSIC",
            "English",
            "2h 15m",
            "$36,000,000.00",
            "$433,888,866.00",
            "7.7",
            "2018",
            "Lady Gaga, Bradley Cooper"
        ),
        DataModel(
            "Alita: Battle Angel ",
            "   When Alita awakens with no memory of who she is in a future world she does not recognize, she is taken in by Ido, a compassionate doctor who realizes that somewhere in this abandoned cyborg shell is the heart and soul of a young woman with an extraordinary past.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/xRWht48C2V8XNfzvPehyClOvDni.jpg",
            "ACTION, SCIENCE FICTION, THRILLER",
            "English",
            "2h 2m",
            "$170,000,000.00",
            "$404,852,543.00",
            "7.5",
            "2019",
            "Rosa Salazar, Christoph Waltz"
        ),
        DataModel(
            "Bohemian Rhapsody",
            "   Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg",
            "DRAMA, MUSIC",
            "English",
            "2h 15m",
            "$52,000,000.00",
            "$835,137,710.00",
            "8.0",
            "2018",
            "Rami Malek, Lucy Boynton"
        ),
        DataModel(
            "Incredibles 2",
            "   Elastigirl springs into action to save the day, while Mr. Incredible faces his greatest challenge yet – taking care of the problems of his three children.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg",
            "ACTION, ADVENTURE, ANIMATION, FAMILY",
            "English",
            "1h 58m",
            "$200,000,000.00",
            "$1,241,891,456.00",
            "7.7",
            "2018",
            "Craig T. Nelson, Holly Hunter"
        ),
        DataModel(
            "Spider-Man: Far from Home",
            "   Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/rjbNpRMoVvqHmhmksbokcyCr7wn.jpg",
            "ACTION, ADVENTURE,SCIENCE FICTION",
            "English",
            "2h 9m",
            "$160,000,000.00",
            "$580,055,628.00",
            "7.7",
            "2019",
            "Tom Holland, Samuel L. Jackson"
        ),
        DataModel(
            "Toy Story 4",
            "   Woody has always been confident about his place in the world and that his priority is taking care of his kid, whether that's Andy or Bonnie. But when Bonnie adds a reluctant new toy called \"Forky\" to her room, a road trip adventure alongside old and new friends will show Woody how big the world can be for a toy.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/w9kR8qbmQ01HwnvK4alvnQ2ca0L.jpg",
            "ADVENTURE, ANIMATION, COMEDY",
            "English",
            "1h 40m",
            "$175,000,000.00",
            "$519,802,847.00",
            "8.3",
            "2019",
            "Tom Hanks, Tim Allen"
        ),
        DataModel(
            "John Wick: Chapter 3 – Parabellum",
            "   Super-assassin John Wick returns with a $14 million price tag on his head and an army of bounty-hunting killers on his trail. After killing a member of the shadowy international assassin’s guild, the High Table, John Wick is excommunicado, but the world’s most ruthless hit men and women await his every turn.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg",
            "CRIME, ACTION, THRILLER",
            "English",
            "2h 11m",
            "$55,000,000.00",
            "$293,061,998.00",
            "8.0",
            "2019",
            "Keanu Reeves, Halle Berry"
        ),
        DataModel(
            "Aladdin",
            "   A kindhearted street urchin named Aladdin embarks on a magical adventure after finding a lamp that releases a wisecracking genie while a power-hungry Grand Vizier vies for the same lamp that has the power to make their deepest wishes come true.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/3iYQTLGoy7QnjcUYRJy4YrAgGvp.jpg",
            "ADVENTURE, FANTASY, ROMANCE",
            "English",
            "2h 10m",
            "$183,000,000.00",
            "$735,831,017.00",
            "7.4",
            "2019",
            "Will Smith, Mena Massoud"
        ),
        DataModel(
            "Avengers: Infinity War",
            "   As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
            "ADVENTURE, ACTION, FANTASY",
            "English",
            "2h 29m",
            "$300,000,000.00",
            "$2,046,239,637.00",
            "8.5",
            "2018",
            "Robert Downey Jr., Chris Hemsworth"
        ),
        DataModel(
            "Spider-Man: Into the Spider-Verse",
            "   Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson \"Kingpin\" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
            "ACTION, ADVENTURE, ANIMATION",
            "English",
            "1h 57m",
            "$90,000,000.00",
            "$375,450,417.00",
            "8.5",
            "2018",
            "Shameik Moore, Jake Johnson"
        )
    )

    fun generateSerial(): List<DataModel> = listOf(
        DataModel(
            "Money Heist",
            "   To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/MoEKaPFHABtA1xKoOteirGaHl1.jpg",
            "CRIME, DRAMA",
            "Spanish; Castilian",
            "70m, 47m",
            "-",
            "-",
            "8.5",
            "2017",
            "Alba Flores, Pedro Alonso"
        ),
        DataModel(
            "The Flash",
            "   After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only 'meta-human' who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/fki3kBlwJzFp8QohL43g9ReV455.jpg",
            "DRAMA, SCIFI & FANTASY",
            "English",
            "44m",
            "-",
            "-",
            "7.8",
            "2014",
            "Grant Gustin, Candice Patton"
        ),
        DataModel(
            "Legion",
            "   David Haller, AKA Legion, is a troubled young man who may be more than human. Diagnosed as schizophrenic, David has been in and out of psychiatric hospitals for years. But after a strange encounter with a fellow patient, he’s confronted with the possibility that the voices he hears and the visions he sees might be real.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/vT0Zsbm4GWd7llNjgWEtwY0CqOv.jpg",
            "ACTION & ADVENTURE, SCIFI & FANTASY",
            "English",
            "50m",
            "-",
            "-",
            "8.3",
            "2017",
            "Dan Stevens, Rachel Keller"
        ),
        DataModel(
            "Dragon Ball",
            "   Long ago in the mountains, a fighting master known as Gohan discovered a strange boy whom he named Goku. Gohan raised him and trained Goku in martial arts until he died. The young and very strong boy was on his own, but easily managed. Then one day, Goku met a teenage girl named Bulma, whose search for the dragon balls brought her to Goku's home. Together, they set off to find all seven dragon balls in an adventure.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/3wx3EAMtqnbSLhGG8NrqXriCUIQ.jpg",
            "ACTION & ADVENTURE, SCIFI & FANTASY, ANIMATION",
            "Japanese",
            "25m",
            "-",
            "-",
            "8.5",
            "1995",
            " Brice Armstrong, Steve Olson"
        ),
        DataModel(
            "One-Punch Man",
            "   Saitama is a hero who only became a hero for fun. After three years of “special” training, though, he’s become so strong that he’s practically invincible. In fact, he’s too strong—even his mightiest opponents are taken out with a single punch, and it turns out that being devastatingly powerful is actually kind of a bore. With his passion for being a hero lost along with his hair, yet still faced with new enemies every day, how much longer can he keep it going?",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/iE3s0lG5QVdEHOEZnoAxjmMtvne.jpg",
            "ACTION & ADVENTURE, COMEDY, ANIMATION",
            "Japanese",
            "24m",
            "-",
            "-",
            "8.9",
            "2015",
            "Makoto Furukawa, Kaito Ishikawa"
        ),
        DataModel(
            "Family Guy",
            "   Sick, twisted, politically incorrect and Freakin' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he's not very bright but has a passion for movies). The final member of the family is Brian - a talking dog and much more than a pet, he keeps Stewie in check whilst sipping Martinis and sorting through his own life issues.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/gBGUL1UTUNmdRQT8gA1LUV4yg39.jpg",
            "COMEDY, ANIMATION",
            "English",
            "22m",
            "-",
            "-",
            "7.2",
            "2012",
            "Seth MacFarlane, Alex Borstein"
        ),
        DataModel(
            "The 100",
            "   100 years in the future, when the Earth has been abandoned due to radioactivity, the last surviving humans live on an ark orbiting the planet — but the ark won't last forever. So the repressive regime picks 100 expendable juvenile delinquents to send down to Earth to see if the planet is still habitable.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/wBzNjurA8ijJPF21Ggs9nbviIzi.jpg",
            "DRAMA, SCIFI & FANTASY",
            "English",
            "43m",
            "-",
            "-",
            "7.7",
            "2014",
            "Eliza Taylor, Bob Morley"
        ),
        DataModel(
            "The Simpsons",
            "   Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/yTZQkSsxUFJZJe67IenRM0AEklc.jpg",
            "ANIMATION, COMEDY",
            "English",
            "22m",
            "-",
            "-",
            "8.7",
            "1989",
            "Dan Castellaneta, Nancy Cartwright"
        ),
        DataModel(
            "Naruto Shippūden",
            "   Naruto Shippuuden is the continuation of the original animated TV series Naruto.The story revolves around an older and slightly more matured Uzumaki Naruto and his quest to save his friend Uchiha Sasuke from the grips of the snake-like Shinobi, Orochimaru. After 2 and a half years Naruto finally returns to his village of Konoha, and sets about putting his ambitions to work, though it will not be easy, as He has amassed a few (more dangerous) enemies, in the likes of the shinobi organization; Akatsuki.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/zAYRe2bJxpWTVrwwmBc00VFkAf4.jpg",
            "ANIMATION, COMEDY, DRAMA",
            "Japanese",
            "22m",
            "-",
            "-",
            "8.5",
            "2007",
            "Junko Takeuchi, Maile Flanagan"
        ),
        DataModel(
            "Hunter x Hunter",
            "   Twelve-year-old Gon Freecss one day discovers that the father he had always been told was dead was alive and well. His Father, Ging, is a Hunter—a member of society's elite with a license to go anywhere or do almost anything. Gon, determined to follow in his father's footsteps, decides to take the Hunter Examination and eventually find his father to prove himself as a Hunter in his own right. But on the way, he learns that there is more to becoming a Hunter than previously thought, and the challenges that he must face are considered the toughest in the world.",
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/yWBcBIO9OrF3E85C5Arols6QNnG.jpg",
            "ACTION & ADVENTURE, ANIMATION, COMEDY",
            "Japanese",
            "24m",
            "-",
            "-",
            "8.9",
            "2011",
            "Alba Flores, Pedro Alonso"
        )
    )
}